### PR TITLE
WIP: 8 processor rewrite

### PR DESCRIPTION
**Pull request by danielp16**
next step connect rosseta internal API

### CODE REVIEW

**Comment by RoySegall** [comment]
@danielp16 Can we remove the file `ReportProcessor.py`?

**Comment by danielp16** [comment]
I am keeping it as a code example of the old import_data process, but its not part of the working code so yes it can be removed.

**Comment by RoySegall** [comment]
@danielp16 I've done some work. Basically - we need [this](https://github.com/RoySegall/BismarckValidator/pull/22/files#diff-3df452f52a684778d49ba71fb2c53855) to be green. Good luck for us. I'll be offline for now(probably get to it tomorrow). If you're on it - let me know.

**Comment by RoySegall** [comment]
I'm back. Hope to fix this one quickly.

**Comment by RoySegall** [comment]
After some work I saw two issues:
1. The first column is ignored - I fixed that.
2. The context of the filed was never acquired. I fixed that as well.

There some errors but I'll fix that later on.

**Comment by RoySegall** [comment]
We kind of got it. Now - to write tests.

**Pull request merged**
